### ISSUE TITLE
Connection manager button text

### ISSUE THREAD

**Issue by sberegszaszi** [KGergo88/RDB_Diplomaterv_Monitor#33]
When opening the application the connection manager button appears like this:

![OpenSerialPort_Button_On_Startup](https://user-images.githubusercontent.com/51827363/88174546-bf624980-cc24-11ea-8231-6ab94003fc19.png)

After successfuly connecting to a port it appears like this:

![OpenSerialPort_Button_After_Successful_Connection](https://user-images.githubusercontent.com/51827363/88174576-cb4e0b80-cc24-11ea-84da-add641f2b6fb.png)

The "Close Serial Port" text is not editable.

The port can be close by pressing the connection manager button again:

![OpenSerialPort_Button_After_Closing_Connection](https://user-images.githubusercontent.com/51827363/88174607-d739cd80-cc24-11ea-8127-49a30f133293.png)

The "Open Serial Port" text is now editable.

Goal would be to have the button text change to "Close Serial Port" after successful connection and have the port name still appear in the text box but as not editable. After closing the connection, the button text would change back to "Open Serial Port" and the port name would be editable again.

**Comment by KGergo88** [comment]
Good catch! :)
